<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf4c10837f6a659afab00c43a0e4aee41
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf4c10837f6a659afab00c43a0e4aee41::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf4c10837f6a659afab00c43a0e4aee41::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf4c10837f6a659afab00c43a0e4aee41::$classMap;

        }, null, ClassLoader::class);
    }
}
